#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)


container_version() {
 /usr/bin/nvim --version | head -1 | awk -F 'v' '{print $2}'
 # echo "0.0.0"
}

container_entrypoint() {
 # WETTY_USER="$(/usr/bin/whoami)"
 # WETTY_TITLE="Code Server"
 # WETTY_COMMAND="/bin/zsh"

 ## Make the server ssh key on start
 # if [ ! -f "/etc/ssh/ssh_host_rsa_key" ] ; then
 #  /usr/bin/sudo /usr/bin/ssh-keygen -A -t rsa -N ''
 # fi
 ## Launch the ssh daemon
 # /usr/bin/sudo /bin/mkdir -p /run/sshd
 # /usr/bin/sudo /usr/sbin/sshd

 ## Setup the local ssh keys
 # if [ ! -f /home/$WETTY_USER/.ssh/id_rsa ] ; then
 #  /bin/mkdir /home/$WETTY_USER/.ssh
 #  /bin/chmod 700 /home/$WETTY_USER/.ssh
 #  /usr/bin/ssh-keygen -t rsa -N '' -f /home/$WETTY_USER/.ssh/id_rsa
 #  /bin/cp /home/$WETTY_USER/.ssh/id_rsa.pub /home/$WETTY_USER/.ssh/authorized_keys
 #  /bin/chmod 600 /home/$WETTY_USER/.ssh/authorized_keys
 # fi

 # /bin/mkdir -p /mnt/volumes/container/Backup \
 #               /mnt/volumes/container/Compose \
 #               /mnt/volumes/container/Container \
 #               /mnt/volumes/container/Workspace

 # /usr/local/bin/wetty --port 8080 --ssh-host localhost --ssh-user $WETTY_USER \
 #                                   --ssh-auth publickey --ssh-key /home/$WETTY_USER/.ssh/id_rsa --force-ssh \
 #                                   --title $WETTY_TITLE --command $WETTY_COMMAD --log-level debug
 # /usr/bin/tmux new -s deven
 /usr/bin/tail -f /dev/null
}
